const { onCall, HttpsError } = require('firebase-functions/v2/https');
const { onDocumentCreated } = require('firebase-functions/v2/firestore');
const { setGlobalOptions } = require('firebase-functions/v2');
const admin = require('firebase-admin');
admin.initializeApp();
setGlobalOptions({region:'us-central1',maxInstances:20});
const db=admin.firestore(), FieldValue=admin.firestore.FieldValue;
const ALLOWED=['بنكك','فوري','أوكاش','ماي كاشي'];
function uid(ctx){if(!ctx.auth)throw new HttpsError('unauthenticated','يجب تسجيل الدخول');if(ctx.auth.token.email_verified!==true)throw new HttpsError('failed-precondition','تحقق من بريدك الإلكتروني أولاً');return ctx.auth.uid;}
async function user(u){const s=await db.doc(`users/${u}`).get();if(!s.exists)throw new HttpsError('not-found','الحساب غير موجود');return s.data();}
async function mustAdmin(ctx){uid(ctx);const u=await user(ctx.auth.uid);if(ctx.auth.token.admin!==true && u.role!=='admin')throw new HttpsError('permission-denied','صلاحية الإدارة مطلوبة');return u;}
exports.touchActivity=onCall(async({auth})=>{const u=uid({auth});const day=new Date().toISOString().slice(0,10);await db.doc(`users/${u}`).set({lastActiveAt:FieldValue.serverTimestamp(),activeDays:FieldValue.arrayUnion(day)},{merge:true});return {ok:true};});
exports.createOrder=onCall(async({auth,data})=>{const u=uid({auth}), me=await user(u);if(me.role!=='customer')throw new HttpsError('permission-denied','العميل فقط');if(!me.isActive||me.isBlocked)throw new HttpsError('failed-precondition','الحساب غير مفعل');if(Number(me.walletBalance||0)<=0)throw new HttpsError('failed-precondition','يجب شحن المحفظة أولاً');const {from,to,type,description,pricingMode,price}=data||{};if(!from||!to)throw new HttpsError('invalid-argument','الاستلام والوجهة مطلوبان');if(pricingMode==='customer'&&(!Number(price)||Number(price)<=0))throw new HttpsError('invalid-argument','السعر مطلوب');if(pricingMode==='customer'&&Number(price)>Number(me.walletBalance||0))throw new HttpsError('failed-precondition','الرصيد لا يكفي');const ref=db.collection('orders').doc();await ref.set({customerId:u,customerName:me.name,customerPhone:me.phone,driverId:null,driverName:null,driverPhone:null,from,to,type:type||'أخرى',description:description||'',pricingMode:pricingMode||'customer',price:pricingMode==='customer'?Number(price):null,status:'pending',reservedCommission:0,companyCommission:0,customerConfirmed:false,createdAt:FieldValue.serverTimestamp(),acceptedAt:null,pickedUpAt:null,driverDeliveredAt:null,completedAt:null,durationSeconds:null});return {id:ref.id};});
exports.acceptOrder=onCall(async({auth,data})=>{const u=uid({auth}), me=await user(u);if(me.role!=='driver'||!me.isActive||me.isBlocked)throw new HttpsError('failed-precondition','حساب السائق غير مفعل');const ref=db.doc(`orders/${data.orderId}`);await db.runTransaction(async t=>{const os=await t.get(ref);if(!os.exists||os.data().status!=='pending')throw new HttpsError('aborted','الطلب لم يعد متاحاً');const o=os.data();if(!o.price||o.price<=0)throw new HttpsError('failed-precondition','السعر لم يحدد بعد');const fee=Number(o.price)*0.05;const us=db.doc(`users/${u}`), uds=await t.get(us),bal=Number(uds.data().walletBalance||0);if(bal<fee)throw new HttpsError('failed-precondition','رصيد المحفظة لا يكفي لحجز عمولة 5%');t.update(us,{walletBalance:bal-fee});t.update(ref,{driverId:u,driverName:me.name,driverPhone:me.phone,status:'accepted',reservedCommission:fee,acceptedAt:FieldValue.serverTimestamp()});t.create(db.collection('transactions').doc(),{userId:u,type:'commission_hold',label:'حجز عمولة 5%',amount:-fee,orderId:ref.id,createdAt:FieldValue.serverTimestamp()});});return {ok:true};});
exports.updateOrderStatus=onCall(async({auth,data})=>{const u=uid({auth}), me=await user(u),ref=db.doc(`orders/${data.orderId}`);const allowed={picked_up:'accepted',driver_delivered:'picked_up'};if(me.role!=='driver')throw new HttpsError('permission-denied','السائق فقط');await db.runTransaction(async t=>{const s=await t.get(ref);if(!s.exists)throw new HttpsError('not-found','الطلب غير موجود');const o=s.data();if(o.driverId!==u||o.status!==allowed[data.status])throw new HttpsError('failed-precondition','حالة الطلب غير صالحة');const patch={status:data.status};if(data.status==='picked_up')patch.pickedUpAt=FieldValue.serverTimestamp();if(data.status==='driver_delivered')patch.driverDeliveredAt=FieldValue.serverTimestamp();t.update(ref,patch);});return {ok:true};});
exports.confirmDelivery=onCall(async({auth,data})=>{const u=uid({auth}), me=await user(u),ref=db.doc(`orders/${data.orderId}`);if(me.role!=='customer')throw new HttpsError('permission-denied','العميل فقط');await db.runTransaction(async t=>{const os=await t.get(ref);if(!os.exists)throw new HttpsError('not-found','الطلب غير موجود');const o=os.data();if(o.customerId!==u||o.status!=='driver_delivered')throw new HttpsError('failed-precondition','الطلب ليس جاهزاً للتأكيد');const cr=db.doc(`users/${o.customerId}`),dr=db.doc(`users/${o.driverId}`),cs=await t.get(cr),ds=await t.get(dr),cb=Number(cs.data().walletBalance||0),dbal=Number(ds.data().walletBalance||0),price=Number(o.price||0),fee=Number(o.reservedCommission||price*0.05),earn=price-fee;if(cb<price)throw new HttpsError('failed-precondition','رصيد العميل لا يكفي لإكمال الطلب');t.update(cr,{walletBalance:cb-price});t.update(dr,{walletBalance:dbal+earn});const duration=(o.acceptedAt&&o.driverDeliveredAt)?Math.max(0,Math.floor((o.driverDeliveredAt.toDate()-o.acceptedAt.toDate())/1000)):null;t.update(ref,{status:'completed',customerConfirmed:true,companyCommission:fee,completedAt:FieldValue.serverTimestamp(),durationSeconds:duration});t.create(db.collection('transactions').doc(),{userId:o.customerId,type:'order_payment',label:'دفع طلب توصيل',amount:-price,orderId:ref.id,createdAt:FieldValue.serverTimestamp()});t.create(db.collection('transactions').doc(),{userId:o.driverId,type:'earning',label:'أرباح توصيل 95%',amount:earn,orderId:ref.id,createdAt:FieldValue.serverTimestamp()});t.create(db.collection('transactions').doc(),{userId:'__company__',type:'commission',label:'عمولة الشركة 5%',amount:fee,orderId:ref.id,createdAt:FieldValue.serverTimestamp()});});return {ok:true};});
exports.commentOnOrder=onCall(async({auth,data})=>{const u=uid({auth}),me=await user(u),text=String(data.text||'').slice(0,500);const ref=db.collection('orderComments').doc();await ref.set({orderId:data.orderId,userId:u,userName:me.name,userRole:me.role,text,createdAt:FieldValue.serverTimestamp()});await db.doc(`orders/${data.orderId}`).set({lastComment:text,lastCommentBy:u,lastCommentAt:FieldValue.serverTimestamp()},{merge:true});return {ok:true};});
exports.rateOrder=onCall(async({auth,data})=>{const u=uid({auth}),me=await user(u),ref=db.doc(`orders/${data.orderId}`),os=await ref.get();if(!os.exists||os.data().customerId!==u||os.data().status!=='completed')throw new HttpsError('failed-precondition','لا يمكن التقييم قبل اكتمال الطلب');await db.collection('ratings').add({orderId:ref.id,customerId:u,driverId:os.data().driverId,rating:Math.max(1,Math.min(5,Number(data.rating))),comment:String(data.comment||'').slice(0,500),createdAt:FieldValue.serverTimestamp()});return {ok:true};});
exports.submitTopup=onCall(async({auth,data})=>{const u=uid({auth}),me=await user(u),amount=Number(data.amount),purpose=data.purpose||'wallet';if(!ALLOWED.includes(data.method)||!amount||amount<=0||!data.receiptUrl)throw new HttpsError('invalid-argument','بيانات الشحن غير صحيحة');if(purpose==='activation' && me.role==='driver' && me.activationFeePaid)throw new HttpsError('failed-precondition','رسوم التفعيل مدفوعة مسبقاً');if(purpose==='activation' && me.role!=='driver')throw new HttpsError('permission-denied','رسوم التفعيل للسائق فقط');if(purpose==='activation' && amount!==10000)throw new HttpsError('invalid-argument','رسوم التفعيل 10,000 جنيه');await db.collection('topups').add({userId:u,userName:me.name,purpose,amount,method:data.method,receiptUrl:data.receiptUrl,receiptName:data.receiptName||'',status:'pending',createdAt:FieldValue.serverTimestamp()});return {ok:true};});
exports.reviewTopup=onCall(async({auth,data})=>{await mustAdmin({auth});const ref=db.doc(`topups/${data.topupId}`);await db.runTransaction(async t=>{const s=await t.get(ref);if(!s.exists||s.data().status!=='pending')throw new HttpsError('failed-precondition','طلب الشحن ليس معلقاً');const x=s.data();if(!data.approve){t.update(ref,{status:'rejected',reviewedAt:FieldValue.serverTimestamp()});return;}const uref=db.doc(`users/${x.userId}`),us=await t.get(uref),bal=Number(us.data().walletBalance||0);if(x.purpose==='activation'){t.update(uref,{activationFeePaid:true});}else{t.update(uref,{walletBalance:bal+Number(x.amount)});t.create(db.collection('transactions').doc(),{userId:x.userId,type:'topup',label:'شحن محفظة',amount:Number(x.amount),source:x.method,createdAt:FieldValue.serverTimestamp()});}t.update(ref,{status:'approved',reviewedAt:FieldValue.serverTimestamp()});});return {ok:true};});
exports.requestWithdrawal=onCall(async({auth,data})=>{const u=uid({auth}),me=await user(u),amount=Number(data.amount);if(me.role!=='driver'||!me.isActive)throw new HttpsError('permission-denied','السائق المفعّل فقط');if(!ALLOWED.includes(data.method)||!amount||amount<=0)throw new HttpsError('invalid-argument','بيانات السحب غير صحيحة');await db.runTransaction(async t=>{const usref=db.doc(`users/${u}`),us=await t.get(usref),bal=Number(us.data().walletBalance||0);if(bal<amount)throw new HttpsError('failed-precondition','الرصيد لا يكفي');t.update(usref,{walletBalance:bal-amount});t.create(db.collection('withdrawals').doc(),{userId:u,userName:me.name,amount,method:data.method,account:String(data.account||''),status:'pending',createdAt:FieldValue.serverTimestamp()});t.create(db.collection('transactions').doc(),{userId:u,type:'withdraw_hold',label:'حجز مبلغ سحب',amount:-amount,createdAt:FieldValue.serverTimestamp()});});return {ok:true};});
exports.reviewWithdrawal=onCall(async({auth,data})=>{await mustAdmin({auth});const ref=db.doc(`withdrawals/${data.withdrawalId}`);await db.runTransaction(async t=>{const s=await t.get(ref);if(!s.exists||s.data().status!=='pending')throw new HttpsError('failed-precondition','طلب السحب ليس معلقاً');const x=s.data();if(data.approve)t.update(ref,{status:'approved',reviewedAt:FieldValue.serverTimestamp()});else{const uref=db.doc(`users/${x.userId}`),us=await t.get(uref),bal=Number(us.data().walletBalance||0);t.update(uref,{walletBalance:bal+Number(x.amount)});t.update(ref,{status:'rejected',reviewedAt:FieldValue.serverTimestamp()});t.create(db.collection('transactions').doc(),{userId:x.userId,type:'withdraw_refund',label:'إرجاع سحب مرفوض',amount:Number(x.amount),createdAt:FieldValue.serverTimestamp()});}});return {ok:true};});
exports.reviewUserActivation=onCall(async({auth,data})=>{await mustAdmin({auth});const ref=db.doc(`users/${data.userId}`);const s=await ref.get();if(!s.exists)throw new HttpsError('not-found','المستخدم غير موجود');const x=s.data();if(!data.approve){await ref.set({activationRejected:true,lastReviewAt:FieldValue.serverTimestamp()},{merge:true});return {ok:true};}if(x.role==='driver' && !x.activationFeePaid)throw new HttpsError('failed-precondition','رسوم تفعيل السائق لم تتم الموافقة عليها');if(!x.identityUrl||!x.residence||x.privacyAccepted!==true||x.termsAccepted!==true||Number(x.age||0)<18)throw new HttpsError('failed-precondition','بيانات التفعيل أو الموافقة ناقصة');if(x.role==='driver' && (!x.stickerUrl||!x.ownerProofUrl))throw new HttpsError('failed-precondition','مستندات السائق ناقصة');if(x.role!=='admin' && x.email && (await admin.auth().getUser(data.userId)).emailVerified!==true)throw new HttpsError('failed-precondition','يجب التحقق من البريد');await ref.set({isActive:true,activationRejected:false,lastReviewAt:FieldValue.serverTimestamp()},{merge:true});return {ok:true};});
exports.setAdminRole=onCall(async({auth,data})=>{await mustAdmin({auth});const email=String(data.email||'').trim();if(!email)throw new HttpsError('invalid-argument','البريد مطلوب');const user=await admin.auth().getUserByEmail(email);await admin.auth().setCustomUserClaims(user.uid,{...(user.customClaims||{}),admin:true});await db.doc(`users/${user.uid}`).set({role:'admin',isActive:true},{merge:true});return {ok:true};});
exports.adminSetOrderPrice=onCall(async({auth,data})=>{await mustAdmin({auth});const price=Number(data.price);if(!price||price<=0)throw new HttpsError('invalid-argument','السعر غير صحيح');const ref=db.doc(`orders/${data.orderId}`);const s=await ref.get();if(!s.exists)throw new HttpsError('not-found','الطلب غير موجود');await ref.set({price,pricingMode:'admin',priceSetBy:auth.uid,priceSetAt:FieldValue.serverTimestamp()},{merge:true});await db.collection('orderPriceEvents').add({orderId:data.orderId,createdAt:FieldValue.serverTimestamp()});return {ok:true};});
async function notifyUsers(ids,title,body){const tokens=[];for(const id of ids){const qs=await db.collection(`users/${id}/tokens`).get();qs.forEach(d=>tokens.push(d.data().token))}for(let i=0;i<tokens.length;i+=500){const batch=tokens.slice(i,i+500);if(batch.length)await admin.messaging().sendEachForMulticast({tokens:batch,notification:{title,body}})}}
exports.notifyNewOrder=onDocumentCreated('orders/{orderId}',async e=>{const d=e.data?.data();if(!d)return;const qs=await db.collection('users').where('role','==','driver').where('isActive','==',true).where('isBlocked','==',false).get();await notifyUsers(qs.docs.map(x=>x.id),'جوان للتوصيل','طلب جديد متاح في بورتسودان')});
exports.notifyPricedOrder=onDocumentCreated('orderPriceEvents/{eventId}',async e=>{const d=e.data?.data();if(!d)return;const qs=await db.collection('users').where('role','==','driver').where('isActive','==',true).where('isBlocked','==',false).get();await notifyUsers(qs.docs.map(x=>x.id),'جوان للتوصيل','تم تحديد سعر طلب جديد وأصبح جاهزاً للسائقين')});
exports.notifyTopup=onDocumentCreated('topups/{topupId}',async e=>{const qs=await db.collection('users').where('role','==','admin').get();await notifyUsers(qs.docs.map(x=>x.id),'طلب شحن جديد','وصل طلب شحن يحتاج مراجعة')});
